### PR TITLE
Travis: connection refused for dind container

### LINKED ISSUE #320: Sporadic Travis build failure with "Machine is not clean" message
```
02:17:09 [ERROR] CloudSlang build for repository: "/home/travis/build/CloudSlang/cloud-slang-content" failed due to failed tests.
02:17:09 [ERROR] Following 4 tests failed:
02:17:09 [ERROR] - Test case failed: test_clear_host_success - Tests that clear host removes all containers and images from host
		Expected result: SUCCESS
		Actual result: MACHINE_IS_NOT_CLEAN
02:17:09 [ERROR] - Test case failed: testSSHBasicallyWorks - Tests ssh actually works
		Expected result: SUCCESS
		Actual result: FAILURE
02:17:09 [ERROR] - Test case failed: test_get_info_success - Tests that flow works - information was retrieved successfully
		Expected result: SUCCESS
		Actual result: FAILURE
02:17:09 [ERROR] - Test case failed: testDocker_test_mysql_monitor - Tests the operation that monitor a mysql container.
		Expected result: SUCCESS
		Actual result: MACHINE_IS_NOT_CLEAN
02:17:09 [ERROR] 
```
https://travis-ci.org/CloudSlang/cloud-slang-content/jobs/77143814

### PR DESCRIPTION
**Pull request by Bonczidai**
fixes #320 

Signed-off-by: Bonczidai Levente <levente.bonczidai@hp.com>

### CODE REVIEW

**Comment by meirwah** [comment]
why change of order helps in anything?

**Comment by Bonczidai** [comment]
error is `java.net.ConnectException: Connection refused` for dind container -- seems like it does not have enough startup time

so I changed the order of commands: first run the container and then do the rest (download builder tool etc.) -- this will (hopefully) assure enough time for the container to start up correctly so we will not need any additional logic

**Comment by meirwah** [comment]
:+1:

**Comment by meirwah** [comment]
still fails... not enough time maybe?

**Comment by Bonczidai** [comment]
migrated to #326

**Pull request closed without merging**
