### PR TITLE
Upgrade Docker version

### PR DESCRIPTION
**Pull request by Bonczidai**
Signed-off-by: Bonczidai Levente levente.bonczidai@hpe.com

### CODE REVIEW

**Comment by oritstone** [comment]
@SamMarkowitz do we have the Docker version mentioned in our documentation or website?

**Comment by SamMarkowitz** [comment]
Nope. No version mentions that I can find.

**Comment by orius123** [comment]
You should probably upgrade dind version as well.

**Comment by Bonczidai** [comment]
What do you mean by that - where?

(this PR refers to CircleCI Docker version, `dind` is used on Travis)

**Comment by orius123** [comment]
Don't you think we should have same version on both?

**Pull request merged**
