### PR TITLE
Amazon-AWS-Network

### PR DESCRIPTION
**Pull request by mihaitusa**
Slang files for:  Allocate Address, Associate Address, Create Network Interface, Delete Network Interface, Disassociate Address operations.
Signed-off-by: Mihail-Cristian Tusa <mihail-cristian.tusa@hpe.com>

### CODE REVIEW

**Comment by mihaitusa** [comment]
@Bonczidai Please review it!

**Comment by mihaitusa** [comment]
Should be merged after release to MC on cs-jclouds 0.0.10.

**Comment by Bonczidai** [comment]
💯 however we'll need test for it

**Comment by mihaitusa** [comment]
@Tirla-Alin Please add tests sl files as they are already for others!

**Comment by tethryus** [comment]
@Tirla-Alin cs-jclouds-0.0.10 released to MC. Please test the content. If tests pass, it will be merged.

**Comment by Tirla-Alin** [comment]
@tethryus The build passed, this can be merged.

**Comment by tethryus** [comment]
@mihaitusa @Tirla-Alin Everything looks ok, can be merged. Great work 👍

**Pull request merged**
