### PR TITLE
Try diff docker cmd circleci

### PR DESCRIPTION
**Pull request by meirwah**

### CODE REVIEW

**Comment by meirwah** [comment]
does not seem to work:
https://github.com/moul/travis-docker

because:
1.	/var/lib/docker is not persistent across ./run calls, but you can chain command calls in a unique ./run or use docker-compose

It means that between ./run call to under all is deleted(images+containers)

**Comment by orius123** [comment]
Try to chain the test command

**Comment by meirwah** [comment]
that does not make sense...
the dind will be down in the end anyway!

**Comment by orius123** [comment]
It will be down after the tests will run against it

**Comment by meirwah** [comment]
chain  al the cmd in the script part you mean?

**Comment by orius123** [comment]
```yaml
script:
- curl -sLo - http://j.mp/install-travis-docker | sh -xe
- wget https://github.com/CloudSlang/cloud-slang/releases/download/cloudslang-0.7.28/cslang-builder.zip
- unzip cslang-builder.zip -d cslang-builder
- chmod +x cslang-builder/bin/cslang-builder
- ./run 'docker run --privileged -d -p 4444 -p 49153:22 -e PORT=4444 --name docker_host_ssh orius123/dind-ssh &&
 ./cslang-builder/bin/cslang-builder -ts docker'
```

**Comment by orius123** [comment]
It might work..

**Comment by meirwah** [comment]
will try

**Comment by meirwah** [comment]
try at #144

**Comment by meirwah** [comment]
nice catch @orius123 it works!!

**Comment by meirwah** [comment]
:+1:

**Pull request merged**
