### PR TITLE
CI build: Increase droplets startup timeout

### PR DESCRIPTION
**Pull request by Bonczidai**
DO seem to be slow lately

Signed-off-by: Bonczidai Levente <levente.bonczidai@hpe.com>

### CODE REVIEW

**Comment by meirwah** [comment]
did you ask DO support on this??

**Comment by Bonczidai** [comment]
not yet

**Comment by Bonczidai** [comment]
merged #346 into this PR for the build to pass

**Comment by meirwah** [comment]
:+1:

**Pull request merged**
