### PR TITLE
tests for unzip_archive.sl

### PR DESCRIPTION
**Pull request by tudorlesan**

### CODE REVIEW

**Comment by tudorlesan** [comment]
@raskin-aleksandr the flow is supposed to archive the "test" folder, unzip it under "foldertest" name then delete both the folder and the zip. 

The unzipped folder gets deleted ok, but when deleting the zip, the delete operation throws an error with very little info. From what I found on google, it's got to do with zipping operation not closing the file properly.

**Comment by raskin-aleksandr** [comment]
Hi @tudorlesan 
I've changed unzip operation and now it's working as expected. I've checked the test flow you made and error is fixed.

**Comment by meshipeer** [comment]
@raskin-aleksandr please finish cover all the test cases and move to ready for merge when done

**Comment by oritstone** [comment]
@raskin-aleksandr also, don't forget to add copyrights section

**Pull request closed without merging**
