### PR TITLE
updated the description of describe vpc's

### PR DESCRIPTION
**Pull request by manjoosh12**
updated the description of describe vpc's

### CODE REVIEW

**Review by umavanth21 — CHANGES_REQUESTED** [review]
"Describes one or more of your VPCs." - this description doesn't give enough information. Refer AFL

**Comment by manjoosh12** [comment]
> "Describes one or more of your VPCs." - this description doesn't give enough information. Refer AFL

@umavanth  in AFL content they mentioned wrong description so i have taken the description form api document

**Comment by umavanth21** [comment]
> > "Describes one or more of your VPCs." - this description doesn't give enough information. Refer AFL
> 
> @umavanth in AFL content they mentioned wrong description so i have taken the description form api document

What is wrong in AFL CP?

**Comment by manjoosh12** [comment]
> > > "Describes one or more of your VPCs." - this description doesn't give enough information. Refer AFL
> > 
> > 
> > @umavanth in AFL content they mentioned wrong description so i have taken the description form api document
> 
> What is wrong in AFL CP?

this is what i can see in AFL for describe vpc's
image

**Comment by umavanth21** [comment]
/Cloud [2.10.2]/Library/Integrations/Amazon/VPC/Virtual Private Cloud/Describe VPCs
Returns information about your Amazon virtual private clouds (VPC). You can filter the results to return information only about VPCs that match the criteria you specify.

This i s what I see in AFL.

**Comment by manjoosh12** [comment]
> Returns information about your Amazon virtual private clouds (VPC). You can filter the results to return information only about VPCs that match the criteria you specify.

will keep the same for cloudslang

**Comment by umavanth21** [comment]
are u allowing to filter?

**Comment by manjoosh12** [comment]
> are u allowing to filter?

yes there is input 
image

**Comment by umavanth21** [comment]
then specify what are the filters you are allowing similar to AFL. Please refer AFL

**Comment by umavanth21** [comment]
Also go thru all code- vpc_ids: lot of copy paste issue

**Review by umavanth21 — APPROVED** [review]

**Review by ameydwivedi — APPROVED** [review]

**Pull request merged**
