### PR TITLE
added tests for get_sublist.sl operation

### PR DESCRIPTION
**Pull request by andreeapuscas**
Signed off by: Andreea Puscas <andreea.puscas@hpe.com>

### CODE REVIEW

**Comment by mihaitusa** [comment]
@andreeapuscas Please update the branch to solve the conflicts. After that we can merge it.

**Comment by tethryus** [comment]
@mihaitusa @andreeapuscas the operation was renamed back to trim_list and the behavior has changed. 

The operation was re-written in java and it handles only strings now. The tests have to be changed in order to reflect the change in behavior.

**Comment by mihaitusa** [comment]
@andreeapuscas  See the comment above (from @tethryus ). Please handle.

**Comment by mihaitusa** [comment]
@andreeapuscas  Please update the branch and sync with @tethryus to solve the tests. When all that are ready then please assign me as review-er in order to merge and close this PR.

**Comment by andreeapuscas** [comment]
The old tests are not valid anymore for this operation.
This operation needs another tests with different scenarios than those in the old commit.

**Pull request closed without merging**
