### PR TITLE
Travis failure - try - nr2

### LINKED ISSUE #320: Sporadic Travis build failure with "Machine is not clean" message
```
02:17:09 [ERROR] CloudSlang build for repository: "/home/travis/build/CloudSlang/cloud-slang-content" failed due to failed tests.
02:17:09 [ERROR] Following 4 tests failed:
02:17:09 [ERROR] - Test case failed: test_clear_host_success - Tests that clear host removes all containers and images from host
		Expected result: SUCCESS
		Actual result: MACHINE_IS_NOT_CLEAN
02:17:09 [ERROR] - Test case failed: testSSHBasicallyWorks - Tests ssh actually works
		Expected result: SUCCESS
		Actual result: FAILURE
02:17:09 [ERROR] - Test case failed: test_get_info_success - Tests that flow works - information was retrieved successfully
		Expected result: SUCCESS
		Actual result: FAILURE
02:17:09 [ERROR] - Test case failed: testDocker_test_mysql_monitor - Tests the operation that monitor a mysql container.
		Expected result: SUCCESS
		Actual result: MACHINE_IS_NOT_CLEAN
02:17:09 [ERROR] 
```
https://travis-ci.org/CloudSlang/cloud-slang-content/jobs/77143814

### PR DESCRIPTION
**Pull request by Bonczidai**
fixes #320 

Signed-off-by: Bonczidai Levente <levente.bonczidai@hp.com>

### CODE REVIEW

**Comment by orius123** [comment]
Does it help to let docker assign the port by itself? Instead of hard coded 49153?

**Comment by Bonczidai** [comment]
nope, it does not help

**Comment by meirwah** [comment]
seem to work?

**Comment by Bonczidai** [comment]
restarting Docker when the issue appears and recreating the container looks promising -- here is a case when it solved the issue:

```
Error response from daemon: Cannot start container aee8e73232bd3415ac1a3a57e20e6967225c3874c8d39d226dfa6d16360a0470: iptables failed: iptables --wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.1 --dport 4444 -j ACCEPT: iptables: No chain/target/match by that name.
 (exit status 1)
*** Container startup failed.. retrying **
CONTAINER ID        IMAGE               COMMAND                CREATED                  STATUS              PORTS               NAMES
aee8e73232bd        orius123/dind-ssh   "/opt/start_sshd.sh"   Less than a second ago                                           docker_host_ssh     
docker_host_ssh
docker_host_ssh
*** Restart Docker ***
docker start/running, process 2310
*** Resetting iptable ***
37a84ec079f5ee4c4a34e99b7176e05b0d4343a61ce3500ab299826bf7aa016b
```

but want to make sure that it works corectly, in another build I got:

```
Error response from daemon: Cannot start container 5962c09f65b54621f7283d2d7c20c9b293e6513397ce7adb66dfd8b0107abf22: iptables failed: iptables --wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.1 --dport 4444 -j ACCEPT: iptables: No chain/target/match by that name.
 (exit status 1)
*** Container startup failed.. retrying **
CONTAINER ID        IMAGE               COMMAND                CREATED                  STATUS              PORTS               NAMES
5962c09f65b5        orius123/dind-ssh   "/opt/start_sshd.sh"   Less than a second ago                                           docker_host_ssh     
docker_host_ssh
docker_host_ssh
*** Restart Docker ***
docker start/running, process 2333
*** Resetting iptable ***
Post http:///var/run/docker.sock/v1.19/containers/create?name=docker_host_ssh: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?
```

btw the issue seems to be Docker related (iptable management from Docker is not really mature)

**Comment by meirwah** [comment]
did you post this issue in Docker or Travis bugs?

**Comment by Bonczidai** [comment]
not yet, at Docker they probably know about it: 

http://stackoverflow.com/questions/30769829/docker-ignores-iptable-rules-when-using-p-portport
https://github.com/docker/docker/issues/10218

**Comment by meirwah** [comment]
weird seems the build was BUILD SUCCESS... : https://travis-ci.org/CloudSlang/cloud-slang-content/jobs/77662023, but build finished with exit code 1...

**Comment by Bonczidai** [comment]
In last build there were 2 situations where the issue happened -- the solution worked for both.. :triumph: 

```
Status: Downloaded newer image for orius123/dind-ssh:latest
Error response from daemon: Cannot start container c3facbcdae0f0e578be0a67941cbce0c32045e0078002ddf5f2c828d2d7f939a: iptables failed: iptables --wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.1 --dport 4444 -j ACCEPT: iptables: No chain/target/match by that name.
 (exit status 1)
*** Container startup failed.. retrying **
CONTAINER ID        IMAGE               COMMAND                CREATED                  STATUS              PORTS               NAMES
c3facbcdae0f        orius123/dind-ssh   "/opt/start_sshd.sh"   Less than a second ago                                           docker_host_ssh     
*** Removing container ***
docker_host_ssh
docker_host_ssh
*** Restart Docker ***
docker start/running, process 2349
*** Resetting iptable ***
docker start/running, process 2349
docker start/running, process 2349
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
8739cf22d19d5c07e65be4caa2805baf46ea4878d18fe5b13d751a22fb221658
```

being hopeful

**Comment by orius123** [comment]
Maybe Travis guys will be able to help configuring the rules, so it will work with docker.  I know nothing about iptables but from that stackoverflow question it looks like configuration issue.

**Comment by Bonczidai** [comment]
migrated to #328

**Pull request closed without merging**
