### PR TITLE
Amazon-AWS-EC2- Query API op's.

### PR DESCRIPTION
**Pull request by mihaitusa**
Signed-off-by: Mihail-Cristian Tusa <mihail-cristian.tusa@hpe.com>

### CODE REVIEW

**Comment by mihaitusa** [comment]
@Bonczidai  Please review it!

**Comment by mihaitusa** [comment]
We will wait until cs-jclouds is released to MC.

**Comment by Bonczidai** [comment]
pretty nice

**Comment by tethryus** [comment]
@mihaitusa GAV version released to MC. It can be merged. Awesome work. +1

**Comment by mihaitusa** [comment]
Waits for #763 to be merged!

**Comment by tethryus** [comment]
:+1:  PR looks great - GAV version released - it's ready to merge! :shipit:

**Pull request merged**
