### PR TITLE
Content Update

### PR DESCRIPTION
**Pull request by tethryus**
Closes: #916 

Applying best practices that will be validated by the builder and CLI.

* new line after @description, @input, @output, @result, 120 # end of description, namespace, @name, @flow/workflow, @outputs, @results.
* Uppercase after @input input_name: O
* Update license to 2017 (current year)
* Add descriptions where needed (the user will have a better understanding of what the desc means).
* Test the content in order to accomodate the new changes in the builder and CLI.
* Fixed content where needed.

Signed-off-by: sorin <sorin@hpe.com>

### CODE REVIEW

**Comment by Bonczidai** [comment]
very nice 👍 is there anything else to add here?

- are these best practices documented somewhere? if not please open an issue
- if any one of these best practices are not yet validated in the builder and you consider it should be, please note on the corresponding issue
- please check Y the build fails

**Comment by tethryus** [comment]
@Bonczidai Fixed the build. There are still some changes left, hopefully today, they will all be finished. Half of the best practices are validated by the builder.

**Comment by tethryus** [comment]
@Bonczidai These changes will be visible at the moment only on the WS_1_0 branch. As soon as the content passes all the validations needed, a pull request will be open on master. The builder now validates all the new changes in the 1.0.3 builder

**Comment by chronical** [comment]
Where are we going to document these best practices? On the cloud-slang-content Wiki? Are we going to create a separate wikidocs page?

**Pull request merged**
