### PR TITLE
updating README with explanation text about command line arguments

### PR DESCRIPTION
**Pull request by lirantal**
Makes it easier for new-comers to adopt the tool and understand command line arguments when working with cslang console for the first time.

### CODE REVIEW

**Comment by meirwah** [comment]
Hey,
we do have "help" capability in the CLI, so users can see the CMD arguments... do you think it's not enough?

I usually do not see other OSS project writing CLI arguments in the README (https://github.com/docker/docker, https://github.com/StackStorm/st2) but they usually put it in the website docs (which we have under : http://www.cloudslang.io/#/docs#cloudslang-cli )

WDYT?

**Comment by lirantal** [comment]
The intention was not to cover all available parameters, but rather to update the final step of running a flow and explaining in a nutshell about the flags so they make sense.

It took me a little while until I figured out the need for the classpath, and it wasn't all that obvious.
I also didn't download the archive but rather just cloned the respective repositories which is what IMHO a lot of people will do.

**Comment by meirwah** [comment]
but in this case.. adding the "--cp ../content/" can be tricky (since it depends where did you download the content repo to).

maybe we need to add a different section for building from source...

**Comment by lirantal** [comment]
You're right, that could be confusing.
Would you like me to work out another section of the README that will go through the steps of building from source for the 2 repositories? (the CLI and the content)

**Comment by meirwah** [comment]
:+1: 
That will be great!

**Pull request merged**
