### PR TITLE
Enhancement base.json

### PR DESCRIPTION
**Pull request by razvan-lupu**
Enhancement for operations in cs-base.json. 
Allows json input with single quotes, returns the result under 'return_result' output field and fixes some defects.

The red highlighted code is caused by RegEx but does not affect the functionality. The GitHub highlighter doesn't like a sequence of characters found in regular expression.

Signed-off-by: Razvan Lupu razvan.lupu@hpe.com

### CODE REVIEW

**Comment by tethryus** [comment]
@razvan-lupu The following test case failed: testGetKeysSingleQuoteSuccess

**Comment by tethryus** [comment]
@razvan-lupu Please update all the operations to include the enhancement requests. Other than that, great job so far.

**Comment by tethryus** [comment]
@Bonczidai Please review.

**Comment by Bonczidai** [comment]
:+1: @tethryus you can merge it - looks good

**Pull request merged**
