### PR TITLE
Bugfix flow restart service

### PR DESCRIPTION
**Pull request by lirantal**
1. Handling of errors/success isn't correctly detecting the actual status of the service restart command. I altered it to accommodate the real status when working in Linux environments.
2. Updated documentation for the flow

### CODE REVIEW

**Comment by meirwah** [comment]
On which Linux distro did you test it?
when I run this flow (with your change) the flow ends with failure, with the next msg:
standard_err = stdin: is not a tty

**Comment by lirantal** [comment]
@meirwah it's on my ubuntu 14.04 
also, if you take a look at the change, I only referred to ```standard_out``` instead of ```standard_err``` which ```standard_out``` is actually available to me through ```publish``` section.

I'm wondering - can you try running the exact same flow on your machine with the 'master' branch and see if you're getting a different response? also which linux dist and how are you running the flow?

**Comment by lirantal** [comment]
@meirwah hey, thanks for looking into this with me today, I found the issue that was confusing us - I used "sudo=1" in the parameters instead of "sudo_user=1" and that's why it was always failing.

Anyway, here you can see a (partial) screenshot of the flow working correctly:

image

can you provide any information on why this doesn't work on your Linux?

**Comment by meirwah** [comment]
@Bonczidai  can you check this flow with another Linux distro?

**Comment by lirantal** [comment]
I also have another workaround to suggest which is to modify the command to
explicitly echo output on success.

For example :
```
service apache2 restart & & echo SUCCESS
```
then we can inspect stdout for that string.

What do you think?

**Comment by meirwah** [comment]
makes sense!

**Comment by lirantal** [comment]
Great.

I'll update the PR.

**Comment by orius123** [comment]
What about using '<command> && exit 0'  and than checking the exit code?

**Comment by lirantal** [comment]
Sadly there's an issue with the return code parameter. If you can fix it
that's great, otherwise we need some safe workaround there.

**Comment by orius123** [comment]
What issue?

**Comment by lirantal** [comment]
@meirwah I updated the flow, check it out.

@orius123 I could be working with the return_code parameter incorrectly, but take a look at this example with the restart_service flow:

I changed the ```restart_service``` flow to use the return_code that the SSH command from the imported script exposes:
image

Then I ran the flow with arguments that I know will make it fail:
image

As you can see return_code is 0 even though the flow failed.
Am I doing something wrong with the return_code usage in the flow or is that an actual defect?

**Comment by orius123** [comment]
I would expect the return code to return code of the command, so I think it's a defect. @meirwah can you look into it?

**Comment by lirantal** [comment]
@orius123 indeed, that's why I was suggesting a safe-bet workaround at least until this issue is solved :-)

**Comment by orius123** [comment]
:+1:

**Comment by Bonczidai** [comment]
checked the flow on Fedora 22 - works :+1:

**Comment by lirantal** [comment]
cool, thanks for confirming! :)

**Pull request merged**
