### PR TITLE
Wrapper pr for stackato content #340

### PR DESCRIPTION
**Pull request by mihaitusa**
closes #334 #340 

Flows for HP Helion Development Platform && Stackato.

### CODE REVIEW

**Comment by mihaitusa** [comment]
@nwright-nz  Please review the modifications.

**Comment by mihaitusa** [comment]
A few best practices to apply on further pull requests:
1. We prefer to use the HTTP Client Post/Put/Get/Delete (from base/network/rest, which are the lightweight variants of the HTTP Client Action) in order to make the REST API calls. So, I changed the operations into flows that uses those clients.
2. Moved content from stackato folder to paas folder and split the content in submodules: applications, services, spaces and users. 
3. Put the authentication flow as a inside step of other flows so that flows can be run standalone.  
4. Added tests for every single flow. 
5. Refactored and renamed as get_resource_details operation to be more generic so that can be used in get_application_details and get_space_details. We try to avoid code duplication. 

@nwright-nz  Thank you for your contribution && for account on HP Helion Development Platform!

**Comment by mihaitusa** [comment]
@gituser173  Please review it as well!

**Comment by gituser173** [comment]
Looks good :+1:

**Comment by mihaitusa** [comment]
@Bonczidai  According to @gituser173 everything is fine. WDYT, we could merge this PR?

**Comment by Bonczidai** [comment]
:+1:

**Pull request merged**
