### PR TITLE
Basic initial content for open shift #350 [2]

### PR DESCRIPTION
**Pull request by mihaitusa**

### CODE REVIEW

**Comment by mihaitusa** [comment]
@mbettan @oritstone  Please review the content. Thanks!

**Comment by mihaitusa** [comment]
A few guidance (best practices) to apply on further pull requests: 
1. We prefer to use the HTTP Client Post/Put/Get/Delete (from base/network/rest, which are the lightweight variants of the HTTP Client Action) in order to make the REST API calls. So, I changed the operations into flows that uses those clients. 
2. The RedHat OpenShift REST API Guide used for calls can be found here: https://access.redhat.com/documentation/en-US/OpenShift/2.0/html/REST_API_Guide/index.html 
3. Moved content from openshift folder to platform_as_a_service folder and split the content in 2 ways: applications and cartridges. 
4. Added tests for every single operation and added list_applications (to complete the test scenarios). 
@mbettan Thank you for your contribution!

**Comment by mbettan** [comment]
Thanks for the review. Why not "paas" instead of " platform_as_a_service" folder ?
Everyone knows today that OpenShift/Cloud Foundry are PaaS platforms. Full name is too heavy in my opinion.

Thanks for the deep review, I will check and test again.

**Comment by meirwah** [comment]
I agree with @mbettan , "paas" is better

**Comment by mihaitusa** [comment]
@mbettan @meirwah  I will change the folder name into "paas" (and all the dependecies). Thanks!

**Comment by mihaitusa** [comment]
Changed the name of the folders from "platform_as_a_service" into "paas". Refactored the flows to be aligned with "task arguments" convention.

**Comment by meirwah** [comment]
@mihaitusa is this ready to merge?

**Comment by mihaitusa** [comment]
@meirwah  Please review the modifications. If everything is ok then it can be merged. Thanks!

**Comment by meirwah** [comment]
:+1:

**Pull request merged**
