### PR TITLE
Getmachine type

### PR DESCRIPTION
**Pull request by manjoosh12**
Created a new operation to get machine_type

### CODE REVIEW

**Review by umavanth21 — COMMENTED** [review]
Please schedule a demo

**Review by umavanth21 — CHANGES_REQUESTED** [review]
Description is not clear

**Comment by sushilMF** [comment]
@manjoosh12 remove the unwanted properties
- trust_all_roots
            - x_509_hostname_verifier
            - trust_keystore
            - trust_password

**Comment by manjoosh12** [comment]
> Description is not clear

@umavanth  updated the description and removed unwanted security properties

**Comment by manjoosh12** [comment]
> @manjoosh12 remove the unwanted properties
> 
> * trust_all_roots
>   - x_509_hostname_verifier
>   - trust_keystore
>   - trust_password

@sushilMF removed these properties .

**Review by umavanth21 — APPROVED** [review]
Approving

**Review by KalyankarRajesh — APPROVED** [review]

**Pull request merged**
