### PR TITLE
fix typos and spelling across source code.

### PR DESCRIPTION
**Pull request by lirantal**
fix typos and spelling across source code
Signed-off-by: Liran Tal liran.tal@gmail.com

### CODE REVIEW

**Comment by lirantal** [comment]
there seem to be some permission issues which fail some of the tests, can you confirm?

**Comment by meirwah** [comment]
Test case failed: test_report_machine_metrics_cAdvisor - Tests SUCCESS case
		Expected result: SUCCESS
		Actual result: C_ADVISOR_CONTAINER_STARTUP_PROBLEM

seems like test is unstable...

**Comment by meirwah** [comment]
re-run and it works.. @Bonczidai  please take a look at that..

**Comment by lirantal** [comment]
@meirwah indeed.

**Comment by oritstone** [comment]
@lirantal , Thanks a lot for your contribution. We will look into it today

**Pull request merged**
