### PR TITLE
Handle zombie droplets - DigitalOcean content

### LINKED ISSUE #285: Sanity check for build env droplets
make sure there are no zombie droplets

### PR DESCRIPTION
**Pull request by Bonczidai**
fixes #285 

Signed-off-by: Bonczidai Levente levente.bonczidai@hpe.com

### CODE REVIEW

**Comment by Bonczidai** [comment]
@mihaitusa please pre-review -- tests need to be added

**Comment by mihaitusa** [comment]
:+1:  @Bonczidai  ... Only thing... check up on first Travis build.

**Comment by Bonczidai** [comment]
Some notes:

- http call's `keepAlive` changed to `false` ( CloudSlang/score-actions#80 )
- added compare_float op (related to #357 )
- instead of waiting an explicit amount of time, I added a a flow (wait_for_status_to_change) based on polling.. the logic becomes more complicated but the flow is more stable and the execution time is reduced --> I think we should all apply this convention instead of `sleep` calls with explicit values

@meirwah @oritstone @SamMarkowitz @mihaitusa @gituser173

**Comment by Bonczidai** [comment]
this content has test which costs 1 additional droplet / build

**Comment by oritstone** [comment]
@gituser173 please review

**Comment by gituser173** [comment]
Looks good :+1:

**Pull request merged**
