### PR TITLE
Wrapper PR for Stackato content [5]

### PR DESCRIPTION
**Pull request by Bonczidai**
closes #334 

Signed-off-by: Bonczidai Levente <levente.bonczidai@hpe.com>

### CODE REVIEW

**Comment by Bonczidai** [comment]
@nwright-nz reviewed your changes :+1: and pulled them in this PR

currently we are investigating how we can add tests for this content - we will merge this PR soon

I will keep you updated, thanks

**Comment by orius123** [comment]
@Bonczidai can we write tests for this? I think we got a OOM again.

**Comment by Bonczidai** [comment]
right, we have an OOM issue ( #337 ) on CircleCI.. to be solved

regarding tests, we will go with local tests for now (automated tests would be even trickier than OpenStack)

**Comment by mihaitusa** [comment]
@nwright-nz  Do you think is possible to talk a bit on lync regarding Stackato? Please give me a sign when it's possible. Thanks!

**Pull request closed without merging**
