### PR TITLE
HP Cloud folder - reviewed comments

### PR DESCRIPTION
**Pull request by SamMarkowitz**
Questions: 

+ list_all_floatingips, get_floatingip_id
  + should we add an underscore before ip as in create_floating_ip, delete_floating_ip, etc?
+ get_server_state_flow
  +  NOTACTIVE (respose) - should we change to NOT_ACTIVE?

### CODE REVIEW

**Comment by Bonczidai** [comment]
please note, on this PR you should have only `hp_cloud` changes (not `google` for example)

I am with the underscore naming ~ create_floating_ip

**Comment by SamMarkowitz** [comment]
My bad. Must have branched off of another branch, instead of master. I'll fix it.

**Comment by Bonczidai** [comment]
:100: 

is this PR ready for merge?

**Comment by SamMarkowitz** [comment]
Nope. I just saw that your comment above included an answer to my questions about the underscores. I will rename them and then it will be ready.

**Pull request merged**
