### PR TITLE
Fix Travis dind problem

### LINKED ISSUE #320: Sporadic Travis build failure with "Machine is not clean" message
```
02:17:09 [ERROR] CloudSlang build for repository: "/home/travis/build/CloudSlang/cloud-slang-content" failed due to failed tests.
02:17:09 [ERROR] Following 4 tests failed:
02:17:09 [ERROR] - Test case failed: test_clear_host_success - Tests that clear host removes all containers and images from host
		Expected result: SUCCESS
		Actual result: MACHINE_IS_NOT_CLEAN
02:17:09 [ERROR] - Test case failed: testSSHBasicallyWorks - Tests ssh actually works
		Expected result: SUCCESS
		Actual result: FAILURE
02:17:09 [ERROR] - Test case failed: test_get_info_success - Tests that flow works - information was retrieved successfully
		Expected result: SUCCESS
		Actual result: FAILURE
02:17:09 [ERROR] - Test case failed: testDocker_test_mysql_monitor - Tests the operation that monitor a mysql container.
		Expected result: SUCCESS
		Actual result: MACHINE_IS_NOT_CLEAN
02:17:09 [ERROR] 
```
https://travis-ci.org/CloudSlang/cloud-slang-content/jobs/77143814

### PR DESCRIPTION
**Pull request by Bonczidai**
fixes #320 

Signed-off-by: Bonczidai Levente <levente.bonczidai@hpe.com>

### CODE REVIEW

**Comment by orius123** [comment]
Don't like the sleep 5. 
Would add variables for `SUCCESS` and `docker_host_ssh`

**Comment by Bonczidai** [comment]
:+1: extracted the variables
I think we need the `sleep` to give enough configuration time for Docker & iptables (but I don't like it either)

**Comment by meirwah** [comment]
:+1:

**Comment by meirwah** [comment]
but I think in the future we need to move/convert some of these scripts to be CloudSlang flows...

**Comment by orius123** [comment]
@Bonczidai can you make a loop that sleeps instead of 5 secs that might/might not be enough?

**Pull request merged**
