### PR TITLE
xml ops and tests

### LINKED ISSUE #360: XML processing

### PR DESCRIPTION
**Pull request by SamMarkowitz**
fixes #360, #532 

Waiting on CloudSlang/score-actions#95.

### CODE REVIEW

**Comment by SamMarkowitz** [comment]
Tested against 0.9.53. Passes.

@mihaitusa please review.

**Comment by mihaitusa** [comment]
@SamMarkowitz  It seems that are some pb with SetValue: Class name io.cloudslang.content.xml.actions.SetValue was not found... Please check it!

**Comment by SamMarkowitz** [comment]
@mihaitusa build passes now with the new builder. Please review.

**Comment by mihaitusa** [comment]
@SamMarkowitz  You can merge it! :ok:

**Pull request merged**
