### PR TITLE
Amazon-AWS-EC2-Classic-E2E

### PR DESCRIPTION
**Pull request by mihaitusa**
Deploy/un-deploy EC2-Classic Instance-E2E Scenario

### CODE REVIEW

**Comment by mihaitusa** [comment]
@Bonczidai  Please review!

**Comment by mihaitusa** [comment]
@Bonczidai  Please review!

**Comment by Bonczidai** [comment]
@mihaitusa looks good! we need tests however

**Comment by mihaitusa** [comment]
@Bonczidai Sure... I'll do it!

**Pull request merged**
