### PR TITLE
Couchbase integration

### PR DESCRIPTION
**Pull request by tethryus**
Information about the integration can be found here:
https://developer.couchbase.com/documentation/server/current/introduction/intro.html

Added buckets, cluster, nodes and views operations.
These operations will be merged once cs-actions/cs-couchbase-0.1.0  will be released to Maven Central.

These operations have been created for the Couchbase integration from https://github.com/CloudSlang/cs-actions/tree/master/cs-couchbase developed by @mihaitusa 

Content created using https://github.com/CloudSlang/cs-content-generator
Added description and default values (features not available yet but will be implemented in the generator).

couchbase-local tests should be added for the operations.

Signed-off-by: Sorin Moldovan <coladdicted@yahoo.com>

### CODE REVIEW

**Comment by mihaitusa** [comment]
looks ok to me...

**Comment by chronical** [comment]
@content-genarator to the rescue

**Comment by tethryus** [comment]
cs-couchbase-0.1.0 has been released to Maven Central: http://search.maven.org/#search%7Cga%7C1%7Ccs-couchbase

**Comment by tethryus** [comment]
Thanks @mihaitusa for developing the Couchbase integration. 👍

**Pull request merged**
