### PR TITLE
OO folder - doc review

### PR DESCRIPTION
**Pull request by SamMarkowitz**
Questions:

+ create_package.sl
  + Should some of the input defaults be removed as they are really just examples?

### CODE REVIEW

**Comment by mihaitusa** [comment]
@SamMarkowitz  Actually the "cp_name" && "cp_version" inputs are not optional. The values are needed to successfully deploy it on Central. The name could be anything and the version has to be major.minor.minor (eg. 1.2.3) to have the correct structure that is needed.

**Comment by SamMarkowitz** [comment]
@mihaitusa - Yes, I understand that they are not optional. What I mean is that the default value is not very useful because it is something that you will need to change 90% of the time. So maybe there shouldn't be a default value at all and the field should be plain old required.

**Comment by mihaitusa** [comment]
@SamMarkowitz  I agree with you!

**Comment by SamMarkowitz** [comment]
@mihaitusa - I'll take them out and send it back to you for one final review.

**Comment by SamMarkowitz** [comment]
@mihaitusa - Build is failing, but it seems unrelated.

**Pull request merged**
