### PR TITLE
Amazon_AWS folder - reviewed comments

### PR DESCRIPTION
**Pull request by SamMarkowitz**

### CODE REVIEW

**Comment by SamMarkowitz** [comment]
Still have the following questions:

+ several flows
  + region - refers to list_regions operation; I don't see any such operation

**Comment by mihaitusa** [comment]
@SamMarkowitz  Check this: https://github.com/CloudSlang/cloud-slang-content/issues/441

**Comment by SamMarkowitz** [comment]
Ok, I see. Then this one is ready to go I think.

**Comment by mihaitusa** [comment]
Yes, for now, is ok IMHO. When we develop a full scale Amazon integration then will treat carefully the description sections.

**Comment by SamMarkowitz** [comment]
@mihaitusa please review when you have a chance.

**Comment by mihaitusa** [comment]
@SamMarkowitz  It looks good! :+1:

**Pull request merged**
